// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SellBook.DataAccess.Data;

#nullable disable

namespace SellBook.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241212075841_ModifySeedDataCategory")]
    partial class ModifySeedDataCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SellBookWeb.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a110"),
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a111"),
                            DisplayOrder = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a112"),
                            DisplayOrder = 3,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a113"),
                            DisplayOrder = 4,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a114"),
                            DisplayOrder = 5,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a115"),
                            DisplayOrder = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a116"),
                            DisplayOrder = 7,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a117"),
                            DisplayOrder = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a118"),
                            DisplayOrder = 9,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a119"),
                            DisplayOrder = 10,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a120"),
                            DisplayOrder = 11,
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a121"),
                            DisplayOrder = 12,
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a122"),
                            DisplayOrder = 13,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a123"),
                            DisplayOrder = 14,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a124"),
                            DisplayOrder = 15,
                            Name = "Art"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a125"),
                            DisplayOrder = 16,
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a126"),
                            DisplayOrder = 17,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a127"),
                            DisplayOrder = 18,
                            Name = "Religion"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a128"),
                            DisplayOrder = 19,
                            Name = "Spirituality"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a129"),
                            DisplayOrder = 20,
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a130"),
                            DisplayOrder = 21,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a131"),
                            DisplayOrder = 22,
                            Name = "Comics"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a132"),
                            DisplayOrder = 23,
                            Name = "Graphic Novels"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a133"),
                            DisplayOrder = 24,
                            Name = "Children's Books"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a134"),
                            DisplayOrder = 25,
                            Name = "Young Adult"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a135"),
                            DisplayOrder = 26,
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a136"),
                            DisplayOrder = 27,
                            Name = "Science"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a137"),
                            DisplayOrder = 28,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a138"),
                            DisplayOrder = 29,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a139"),
                            DisplayOrder = 30,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a140"),
                            DisplayOrder = 31,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a141"),
                            DisplayOrder = 32,
                            Name = "Economics"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a142"),
                            DisplayOrder = 33,
                            Name = "Business"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a143"),
                            DisplayOrder = 34,
                            Name = "Management"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a144"),
                            DisplayOrder = 35,
                            Name = "Law"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a145"),
                            DisplayOrder = 36,
                            Name = "True Crime"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a146"),
                            DisplayOrder = 37,
                            Name = "Anthology"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a147"),
                            DisplayOrder = 38,
                            Name = "Classic"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a148"),
                            DisplayOrder = 39,
                            Name = "Satire"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a149"),
                            DisplayOrder = 40,
                            Name = "Essay"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a150"),
                            DisplayOrder = 41,
                            Name = "Memoir"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a151"),
                            DisplayOrder = 42,
                            Name = "Humor"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a152"),
                            DisplayOrder = 43,
                            Name = "Parenting"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a153"),
                            DisplayOrder = 44,
                            Name = "Relationships"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a154"),
                            DisplayOrder = 45,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a155"),
                            DisplayOrder = 46,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a156"),
                            DisplayOrder = 47,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a157"),
                            DisplayOrder = 48,
                            Name = "Animals"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a158"),
                            DisplayOrder = 49,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = new Guid("8a9b2967-bd3e-4d75-81f5-64c5e191a159"),
                            DisplayOrder = 50,
                            Name = "Environment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
